### ISSUE TITLE
ScaleFast won't launch on fresh install in RF3

### ISSUE THREAD

**Issue by sponcey** [roboDocs/ScaleFast#4]
I've installed the ScaleFast extension from this repository, and it won't launch. I get this output:

`Traceback (most recent call last):
​  File "scaleFast.py", line 1532, in <module>
  File "scaleFast.py", line 387, in __init__
  File "scaleFast.py", line 920, in _selectedFontChanged
  File "/Users/Cadmon/Library/Application Support/RoboFont/plugins/ScaleFast.roboFontExt/lib/mutatorScale/lib/mutatorScale/utilities/fontUtils.py", line 59, in getRefStems
  File "/Users/Cadmon/Library/Application Support/RoboFont/plugins/ScaleFast.roboFontExt/lib/mutatorScale/lib/mutatorScale/utilities/fontUtils.py", line 127, in freezeGlyph
  File "/Users/Cadmon/Library/Application Support/RoboFont/plugins/ScaleFast.roboFontExt/lib/mutatorScale/lib/mutatorScale/utilities/fontUtils.py", line 177, in extractComposites
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.6/fontParts/base/deprecated.py", line 77, in transform
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.6/fontParts/base/base.py", line 466, in transformBy
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.6/fontParts/base/normalizers.py", line 999, in normalizeTransformationMatrix
TypeError: Transformation matrices must be tuple instances, not Transform.
`

**Comment by gferreira** [comment]
ok, found it 🐞 should be fixed with d32aad4

can you please download, re-install & try again? thanks!

**Comment by sponcey** [comment]
Thanks for that fix! Reinstalled and ran, still not launching, and getting this error in the output instead:

`Traceback (most recent call last):
​  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.6/fontParts/base/component.py", line 278, in _drawPoints
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.6/fontTools/pens/pointPen.py", line 204, in addComponent
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.6/fontTools/pens/basePen.py", line 177, in addComponent
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scaleFast.py", line 1532, in <module>
  File "scaleFast.py", line 387, in __init__
  File "scaleFast.py", line 920, in _selectedFontChanged
  File "/Users/Cadmon/Library/Application Support/RoboFont/plugins/ScaleFast.roboFontExt/lib/mutatorScale/lib/mutatorScale/utilities/fontUtils.py", line 64, in getRefStems
  File "/Users/Cadmon/Library/Application Support/RoboFont/plugins/ScaleFast.roboFontExt/lib/mutatorScale/lib/mutatorScale/utilities/fontUtils.py", line 252, in getGlyphBox
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.6/fontParts/base/glyph.py", line 620, in draw
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.6/fontParts/base/component.py", line 252, in draw
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.6/fontParts/base/component.py", line 260, in _draw
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.6/fontParts/base/component.py", line 266, in drawPoints
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.6/fontParts/base/component.py", line 280, in _drawPoints
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.6/fontTools/pens/pointPen.py", line 204, in addComponent
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.6/fontTools/pens/basePen.py", line 177, in addComponent
TypeError: 'NoneType' object is not subscriptable`

**Comment by gferreira** [comment]
your [question in the RF forum](https://forum.robofont.com/topic/634/component-in-background-layers-not-visible) gives a clue: it looks like the base glyph for a component is missing.

I can launch and use ScaleFast without any problems, so it will probably work if you fix the font data.
